module.exports = {
    C: 'c',
    CPP: 'cpp',
    PYTHON: 'python',
    JAVA: 'java',
    NODEJS: 'nodejs',
    JAVASCRIPT: 'javascript',
    GO: 'go',
    PERL: 'perl',
    RUBY: 'ruby',
    PROMPTV1: 'promptv1',
    PROMPTV2: 'promptv2',
    MULTIFILE: 'multifile',
    SQLITE3: 'sqlite3',
}
