module.exports = {
  C: "c",
  CPP: "cpp",
  PYTHON: "python",
  JAVA: "java",
  NODEJS: "nodejs",
  BASH: "bash",
  RUBY: "ruby",
  PROMPTV1: "promptv1",
  PROMPTV2: "promptv2",
  MULTIFILE: "multifile",
  SQLITE3: "sqlite3",
  SWIFT: "swift",
  RUST: "rust",
  C_SHARP: "csharp",
  DART: "dart",
  KOTLIN: "kotlin",
  PHP: "php",
};
