module.exports = {
    C: 'c',
    CPP: 'cpp',
    PYTHON: 'python',
    JAVA: 'java',
    NODEJS: 'nodejs',
    RUBY: 'ruby',
    CSHARP: 'csharp',   
    KOTLIN: 'kotlin',   
    DART: 'dart',
    PROMPTV1: 'promptv1',
    PROMPTV2: 'promptv2',
    MULTIFILE: 'multifile',
    SQLITE3: 'sqlite3',
}
